### ISSUE TITLE
SideBar 자동으로 숨겨지는 기능

### ISSUE THREAD

**Issue by iseolin76** [kimgh06/Pota#1]
<img width="1792" alt="스크린샷 2022-09-14 오후 12 11 24" src="https://user-images.githubusercontent.com/65021545/190050366-a0a5d6c0-adea-4a2a-9c12-365391a6b91a.png">

SideBar외 영역을 클릭해도 감춰지지 않고 그로 인해서 내용물이 가려져요 ㅠ

**Comment by kimgh06** [comment]
sideBar이외의 영역을 클릭해도 감춰지도록 만들겠습니다.
피드백 감사합니다.

**Comment by kimgh06** [comment]
사이드바 이외의 영역을 클릭할 경우, 사이드바가 다시 들어가도록 추가 했습니다.
